name: imgix
description: A Dart client library for generating URLs with imgix
version: 1.0.0
homepage: https://github.com/amondnet/imgix.dart

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  crypto:
  quiver:

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.6.0
  test_coverage: ^0.4.1
  remove_from_coverage: ^1.0.7