name: imgix_client
description: A Dart client library for generating URLs with imgix.
version: 1.0.0+2
homepage: https://github.com/amondnet/imgix_client.dart

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  crypto: ^2.1.4
  quiver: ^2.1.3

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.6.0
  test_coverage: ^0.4.1
  remove_from_coverage: ^1.0.7