name: imgix_client
description: A Dart client library for generating URLs with imgix.
version: 3.0.0
homepage: https://github.com/amondnet/imgix_client.dart

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  crypto: ^3.0.1
  quiver: ^3.0.1
  built_collection: ^5.0.0
dev_dependencies:
  test: ^1.17.4
  test_cov: ^1.0.1
  remove_from_coverage: ^2.0.0
  lints: ^2.0.0