name: imgix_client
description: A Dart client library for generating URLs with imgix.
version: 2.0.0
homepage: https://github.com/amondnet/imgix_client.dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  crypto: ^3.0.1
  quiver: ^3.0.1

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.4
  test_cov: ^1.0.1
  remove_from_coverage: ^2.0.0