name: Build

on: [push, pull_request]

jobs:
  build_dart_packages:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [""]
        sdk: [2.12.0, 2.18.0, stable, beta, dev]

    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - name: Install dependencies
        #working-directory: ${{ matrix.package }}
        run: pub get

      - name: Analyze
        #working-directory: ${{ matrix.package }}
        run: dartanalyzer .
        #--fatal-infos --fatal-warnings .

      - name: Run tests
        #working-directory: ${{ matrix.package }}
        run: |
          pub run test
          pub run test_cov

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: ${{ matrix.package }}
          file: ./${{ matrix.package }}/coverage/lcov.info