name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_dart_packages:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [""]
        sdk: [3.0.0, stable, beta, dev]

    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - name: Install dependencies
        #working-directory: ${{ matrix.package }}
        run: dart pub get

      - name: Analyze
        #working-directory: ${{ matrix.package }}
        run: dart analyze --fatal-infos --fatal-warnings .

      - name: Run tests
        #working-directory: ${{ matrix.package }}
        run: |
          dart run test
          dart run test_cov

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: ${{ matrix.package }}
          file: ./${{ matrix.package }}/coverage/lcov.info